inherit_from: .rubocop_todo.yml

AllCops:
  Excludes:
    - db/schema.rb
    - db/migrate/*

Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
    - 'config/initializers/rswag-api.rb'

Style/HashSyntax:
  Enabled: false
