inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/bundle
    - bin/rails
    - bin/rake
    - bin/setup
    - bin/update
  TargetRubyVersion: 2.5

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'config/initializers/rswag-api.rb'

Style/HashSyntax:
  Enabled: false
