inherit_from: .rubocop_todo.yml

AllCops:
  Excludes:
    - db/schema.rb

Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
    - 'config/initializers/rswag-api.rb'

Style/HashSyntax:
  Enabled: false
