language: ruby
rvm:
  - 2.5
  - 2.6

codecov: true

addons:
  postgresql: "9.6"

env:
  global:
    - TESTOPTS=--verbose
    - PATH_PREFIX=/api
    - APP_NAME=hooks

install:
  - bundle install

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:migrate

script:
  - bundle exec rake rubocop
  - bundle exec rake documentation:generate
  - bundle exec rake test:validate
