version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_SERVER_ID=1
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 29092:29092
    expose:
      - 29092
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
  mcom-redis:
    image: "registry.access.redhat.com/rhscl/redis-32-rhel7"
    ports:
      - 6379:6379
    expose:
      - 6379
    environment:
      REDIS_PASSWORD: redispass
  postgres:
    image: "registry.access.redhat.com/rhscl/postgresql-10-rhel7"
    env_file:
      - postgres.env
    expose:
      - 5432
    ports:
      - 5432:5432
  rails:
    build:
      context: ..
      dockerfile: docker/Dockerfile.rails
    volumes:
      - ..:/app
    command: bin/rails server --binding 0.0.0.0
    env_file:
      - postgres.env
      - app.env
    ports:
      - 3000:3000
    depends_on:
      - postgres
  endpoint:
    build:
      context: ..
      dockerfile: docker/Dockerfile.endpoint
    volumes:
      - ..:/app
    command: bundle exec ruby bin/example_endpoint.rb -o 0.0.0.0
    ports:
      - 4568:4568
      - 4567:4567
    environment:
      TEST_COUNT: ${TEST_COUNT:-1}
  resque:
    build:
      context: ..
      dockerfile: docker/Dockerfile.rails
    volumes:
      - ..:/app
    command: bin/rake environment resque:work
    environment:
      QUEUE: '*'
      REDIS_SERVICE_NAME: mcom-redis
      REDIS_PASSWORD: redispass
      MCOM_REDIS_SERVICE_HOST: mcom-redis
      JOBS_PER_FORK: 50
    env_file:
      - postgres.env
    depends_on:
      - postgres
      - mcom-redis
  resque-scheduler:
    build:
      context: ..
      dockerfile: docker/Dockerfile.rails
    volumes:
      - ..:/app
    command: bin/rake environment resque:scheduler
    environment:
      REDIS_SERVICE_NAME: mcom-redis
      REDIS_PASSWORD: redispass
      MCOM_REDIS_SERVICE_HOST: mcom-redis
    env_file:
      - postgres.env
    depends_on:
      - postgres
      - mcom-redis
  racecar:
    build:
      context: ..
      dockerfile: docker/Dockerfile.rails
    volumes:
      - ..:/app
    command: bundle exec racecar JobCreatorConsumer
    environment:
      KAFKA_BROKER_HOST: kafka
      KAFKA_PORT: 29092
      REDIS_SERVICE_NAME: mcom-redis
      REDIS_PASSWORD: redispass
      MCOM_REDIS_SERVICE_HOST: mcom-redis
    env_file:
      - postgres.env
    depends_on:
      - kafka
      - mcom-redis
      - postgres
    restart: on-failure
  # consumer:
  #   build: ./consumer
  #   image: consumer:latest
  #   depends_on:
  #     - kafka
  # upload-service:
  #   build: ../.
  #   image: upload-service:latest
  #   ports:
  #     - 8080:8888
  #   environment:
  #     - AWS_ACCESS_KEY_ID
  #     - AWS_SECRET_ACCESS_KEY
  #     # set storage driver if not s3
  #     #- STORAGE_DRIVER=localdisk
  #     # set env variables if not using the default
  #     #- S3_PERM
  #     #- S3_REJECT
  #     #- S3_QUARANTINE
  #   depends_on:
  #     - kafka
