version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_SERVER_ID=1
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 29092:29092
    expose:
      - 29092
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
  mcom-redis:
    image: redis
    ports:
      - 6379:6379
    expose:
      - 6379
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
  rails:
    build:
      context: ..
      dockerfile: docker/Dockerfile.rails
    volumes:
      - ..:/app
    command: rails server --binding 0.0.0.0
    ports:
      - 3000:3000
    depends_on:
      - postgres
  resque:
    build:
      context: ..
      dockerfile: docker/Dockerfile.rails
    volumes:
      - ..:/app
    command: rake environment resque:work
    environment:
      QUEUE: '*'
      REDIS_URL: "redis://mcom-redis:6379"
    depends_on:
      - postgres
      - mcom-redis
  racecar:
    build:
      context: ..
      dockerfile: docker/Dockerfile.rails
    volumes:
      - ..:/app
    command: racecar JobCreatorConsumer
    environment:
      KAFKA_BROKER_HOST: kafka
      REDIS_URL: "redis://mcom-redis:6379"
    depends_on:
      - kafka
      - mcom-redis
      - postgres
  # consumer:
  #   build: ./consumer
  #   image: consumer:latest
  #   depends_on:
  #     - kafka
  # upload-service:
  #   build: ../.
  #   image: upload-service:latest
  #   ports:
  #     - 8080:8888
  #   environment:
  #     - AWS_ACCESS_KEY_ID
  #     - AWS_SECRET_ACCESS_KEY
  #     # set storage driver if not s3
  #     #- STORAGE_DRIVER=localdisk
  #     # set env variables if not using the default
  #     #- S3_PERM
  #     #- S3_REJECT
  #     #- S3_QUARANTINE
  #   depends_on:
  #     - kafka
