# These config values will be shared by all environments but can be overridden.
common: &common
  client_id: "tech_test"

development:
  <<: *common
  brokers:
    - <%= ENV['KAFKA_BROKER_HOST'] || 'localhost' %>:29092

test:
  <<: *common
  brokers:
    - localhost:9092

production:
  <<: *common
  brokers:
    - kafka1.myapp.com:9092
    - kafka2.myapp.com:9092
    - kafka3.myapp.com:9092
