# These config values will be shared by all environments but can be overridden.
<% kafka_host = ENV['KAFKA_BROKER_HOST'] || 'localhost' %>
<% kafka_port = ENV['KAFKA_PORT'] || 29092 %>
<% kafka_url = ENV['KAFKAMQ'] ? ENV['KAFKAMQ'] : "#{kafka_host}:#{kafka_port}" %>

common: &common
  client_id: "tech_test"
  brokers:
    - <%= kafka_url %>

development:
  <<: *common

test:
  <<: *common

production:
  <<: *common
